# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSPermission' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SPPermission/Camera'
pod 'SPPermission/Location'
pod 'SPPermission/Microphone'

  # Pods for iOSPermission

end
